### ISSUE TITLE
Crash when running after upgrading to 3.1.25

### ISSUE THREAD

**Issue by jing2uo** [flathub/org.b3log.siyuan#70]
```
 flatpak run org.b3log.siyuan
Debug: Enabling Wayland backend
Debug: Will run Siyuan with the following arguments: --enable-features=Vulkan --ozone-platform-hint=auto --enable-features=UseOzonePlatform,WaylandWindowDecorations --enable-wayland-ime
Debug: Additionally, user gave:
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@electron/remote/main'
Require stack:
- /app/siyuan/resources/app/electron/main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:124485)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/siyuan/resources/app/electron/main.js:35:16)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
```
